# Generated by Django 5.1.4 on 2025-01-23 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('aadhar_number', models.CharField(default='000000000000', max_length=12, unique=True)),
                ('dob', models.CharField(blank=True, default='01012001', max_length=8, null=True)),
                ('library_name', models.CharField(max_length=100)),
                ('seat_capacity', models.IntegerField()),
                ('library_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('address', models.TextField()),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='library.library')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('seat_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('mobile_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='library.student')),
            ],
        ),
    ]
